---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- name: Define apache_perl_packages.
  set_fact:
    apache_perl_packages: "{{ __apache_perl_packages | list }}"
  when: apache_perl_packages is not defined

- name: Define apache_mod_security_packages.
  set_fact:
    apache_mod_security_packages: "{{ __apache_mod_security_packages | list }}"
  when: apache_mod_security_packages is not defined

- name: Define apache_mod_jk_packages.
  set_fact:
    apache_mod_jk_packages: "{{ __apache_mod_jk_packages | list }}"
  when: apache_mod_jk_packages is not defined

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  command: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
  changed_when: false
  check_mode: false
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: Include Apache 2.4 variables.
  include_vars: apache-24.yml
  when: "apache_version.split('.')[1] == '4'"

# Figure out what mpm module of Apache is enabled.
- name: Get enabled mod_mpm of Apache.
  shell: /usr/sbin/apachectl -V | /usr/bin/grep -i mpm | /bin/awk '{print $3}'
  changed_when: false
  check_mode: false
  register: _apache_modmpm_ena

- name: Create apache_mpm_ena variable.
  set_fact:
    apache_mpm_ena: "{{ _apache_modmpm_ena }}"

# Disable Apache Mods mpm
- name: Disable Apache Mods mpm
  include_tasks: "disable.yml"

# Configure Apache mods.
- name: Configure Apache mods.
  include_tasks: "mods-{{ ansible_os_family }}.yml"

# Configure Apache.
- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
